version: '3.3'

services:
  app:
    build:
      context: ./db-proj-app/
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "0.0.0.0:3000:3000"
    restart: always

  backend:
    build:
      context: ./db-proj-backend/
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:8000:8000"
    restart: always